### PR TITLE
Ci to update doc website

### PR DESCRIPTION
**Pull request by etpalmer63**
Puts CI in place, so that docs automatically update and upload to https://erf-model.github.io/docs when a PR is accepted.

### CODE REVIEW

**Comment by rafmudaf** [comment]
@etpalmer63 I've dealt with similar systems in other projects, so let me know if you want to talk through any of the problems you're facing here.

**Comment by etpalmer63** [comment]
@rafmudaf if this one fails, I have to go find more ideas. So I would be happy to have your advice. :smile: Can I find you on slack?

**Comment by rafmudaf** [comment]
> Can I find you on slack?

Yep, I'm on the ERF Slack team.

**Comment by etpalmer63** [comment]
Hi @rafmudaf , can you invite me? I don't yet have access that workgroup. My email is epalmer@lbl.gov

**Pull request closed without merging**
