### PR TITLE
Interface for NOAH-MP Landsurface model

### PR DESCRIPTION
**Pull request by akashdhruv**
The interface is under active development. However, I am creating this PR to ensure that it is integrated with the regression testing framework. Supporting documentation to follow.

### CODE REVIEW

**Comment by akashdhruv** [comment]
Ran local tests after a merge with latest development branch and things are breaking particularly related to this PR: #1833

**Comment by asalmgren** [comment]
@akashdhruv -- there have been more changes to the cmake stuff -- can you try again?

**Comment by akashdhruv** [comment]
> @akashdhruv -- there have been more changes to the cmake stuff -- can you try again?

Ok.

**Comment by akashdhruv** [comment]
This PR is ready for review and merge. Issues related to CMake have been resolved. To ensure that Noah MP interface is included as part of testing I recommend adding following cmake options to the test suite,

`-DERF_ENABLE_NETCDF:BOOL=ON -DNETCDF_DIR=$NETCDF_HOME -DERF_ENABLE_NOAH:BOOL=ON`

Note that using NOAH-MP requires building the Fortran interface for NetCDF. You can find build options for those in shell scripts located here: https://github.com/Lab-Notebooks/ERF-Noah-Coupling/tree/main/software/netcdf

**Pull request merged**
