### PR TITLE
Update submodule AMReX to the latest one

### PR DESCRIPTION
**Pull request by pkjha-aero**

### CODE REVIEW

**Comment by ewquon** [comment]
We should decide how often we want to update the AMReX submodule, or if it makes sense to freeze it for now. Is there a specific version or bug fix that has been pulled in?

**Comment by pkjha-aero** [comment]
@ewquon, I noticed several changes to AMReX code including some fixes (https://github.com/AMReX-Codes/amrex/commit/c143555e74e4096ec25400369651bf884b8561b3, https://github.com/AMReX-Codes/amrex/commit/eb9b4242a07028a77bd95986f5a5686c81dce428). That's why I wanted to update. Though these fixes may not affect us.
But, I agree that we should decide how often we want to update.

**Review by ewquon — APPROVED** [review]

**Comment by ewquon** [comment]
Thanks for the info. I think this is fine, let's plan on freezing the submodule after we pass our next solver milestone.

**Review by xyuan — APPROVED** [review]
I agree with you

**Pull request merged**
