### PR TITLE
Add code coverage and reporting

### PR DESCRIPTION
**Pull request by rafmudaf**
This pull request adds code coverage measurement for the regression tests. It also submits the coverage reports to codecov.io.

Note: the badge on the README currently links to my account on codecov.io but when a new one is created for the `erf-model/ERF` repo I'll update that link.

### CODE REVIEW

**Comment by rafmudaf** [comment]
You can view the current code coverage at https://app.codecov.io/gh/rafmudaf/ERF.

**Comment by rafmudaf** [comment]
When ready to merge, please use "Squash and merge" to combine all of these commits into a single commit in `development`. There are additional commits in my working branch that were used solely for development and won't add any meaning to our future selfs looked back at these commits.

**Comment by ewquon** [comment]
@rafmudaf does it make sense to check the coverage over `Exec` as well as `Submodules`?

**Review by pkjha-aero — APPROVED** [review]

**Comment by rafmudaf** [comment]
> @rafmudaf does it make sense to check the coverage over Exec as well as Submodules?

@ewquon good point, we definitely don't need to track coverage on Submodules. What do you think about Exec?

**Pull request merged**
